version: "3.7"

services:
  slim:
    image: php:8-alpine
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    env_file:
      - ./.env
      - ./.env.local
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
      - ./logs:/var/www/logs
